# Generated by Django 4.1.7 on 2023-03-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('age', models.IntegerField(max_length=30)),
                ('gender', models.CharField(max_length=30)),
                ('phonenumber', models.IntegerField(max_length=30)),
                ('amount', models.IntegerField(max_length=30)),
            ],
        ),
    ]
